name: smartschool
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  carousel_slider: ^4.1.1
  http: ^0.13.5
  dio: ^4.0.6
  buttons_tabbar: ^1.3.6
  shared_preferences: ^2.0.15
  getwidget: ^3.0.1
  file_picker: ^3.0.4
  path: ^1.6.4
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_native_splash: ^2.2.8
  
flutter_native_splash: 
  color: "#000000"
  image: assets/gambar/logosd.png

flutter: 
  uses-material-design: true
  assets:
  - assets/gambar/
  - assets/foto/

